version: '3.9'

services:
  one-blog-db:
    image: 'mysql:8.0.33-oracle'
    environment:
      MYSQL_DATABASE: one-blog
      MYSQL_ROOT_PASSWORD: a12345678
      MYSQL_USER: admin
      MYSQL_PASSWORD: 12345678
    ports:
      - '3306:3306'
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
